BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Machines" (
	"id"	INTEGER,
	"Pname"	TEXT NOT NULL,
	"Code"	INTEGER NOT NULL,
	"Type"	TEXT NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Catalog" (
	"id"	INTEGER,
	"Machinesid"	INTEGER NOT NULL,
	"Suppliersid"	INTEGER NOT NULL,
	"Cost"	INTEGER NOT NULL,
	FOREIGN KEY("Machinesid") REFERENCES "Machines"("id") ON DELETE CASCADE,
	FOREIGN KEY("Suppliersid") REFERENCES "Suppliers"("id") ON DELETE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Suppliers" (
	"id"	INTEGER,
	"Sname"	TEXT NOT NULL,
	"Anddress"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id")
);
COMMIT;
